name: Build and push Perl Kit 1.0 to GitHub Container Registry

on:
  push:
    branches:
      - master
    paths-ignore:
      - .dockerignore
      - .gitignore
      - README.md
      - Vagrantfile

jobs:
  push_to_registry:
    if: github.repository == 'kaworu/perl1'
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/kaworu/perl1-alpine-3.13.2,ghcr.io/kaworu/perl1-alpine-3.13,ghcr.io/kaworu/perl1-alpine
